//
// Created by louis on 15/01/19.
//

#ifndef WEBSOCKETNETWORKING_MESSAGERESULT_H
#define WEBSOCKETNETWORKING_MESSAGERESULT_H

#include <string>

namespace model {
/**
 * @class ActionResult
 *
 * @brief A class for storing the Game's response, associated client's ID, and scope of the output
 *
 * This class stores a response message generated by the game, the recipient client's ID, and
 * a boolean variable that if for determining whether or not the response message should be
 * sent only to the client or to broadcast it to all clients.
 */
    class ActionResult {
    private:
        unsigned long int clientId;
        std::string message;
        bool local;

    public:
        ActionResult();

        unsigned long int getClientId();

        void setClientId(unsigned long int clientId);

        std::string getMessage();

        void setMessage(std::string message);

        void setPublic();

        bool isLocal();
    };
}

#endif //WEBSOCKETNETWORKING_MESSAGERESULT_H
