//
// Created by louis on 15/01/19.
//

#ifndef WEBSOCKETNETWORKING_MESSAGERESULT_H
#define WEBSOCKETNETWORKING_MESSAGERESULT_H

#include <string>

namespace model {
/**
 * @class  GameResponse
 *
 * @brief A class for storing the Game's response, associated client's ID, and scope of the output
 *
 * This class stores a response message generated by the game, the recipient client's ID, and
 * a boolean variable that if for determining whether or not the response message should be
 * sent only to the client or to broadcast it to all clients.
 */
    class GameResponse {
    private:
        unsigned long int clientId;
        std::string message;
        bool local;

    public:
        GameResponse();

        unsigned long int
        getClientId();

        /**
         * Sets the instance's clientId.
         */
        void
        setClientId(unsigned long int clientId);

        /**
         * Returns the instance's message.
         */
        std::string
        getMessage();

        /**
         * Sets the instance's message.
         */
        void
        setMessage(std::string message);

        /**
         * Sets the instance's 'local' member variable to false.
         */
        void
        setPublic();

        /**
         * Returns the value of instance's 'local' member variable. Is used to determine if a response should be sent
         * to one client or many.
         */
        bool
        isLocal();
    };
}

#endif //WEBSOCKETNETWORKING_MESSAGERESULT_H
